Fix m1 signatures
trailofbits/osquery pull request #6
Opened 2021-10-28 15:26 UTC by ameily

This PR attempts to fix the Mac signatures and associated tests for M1 architecture.

- Added the `arm64` architecture to the signature check list.
- Created a small unsigned binary to test against on M1 systems.
- Make additional changes to a signed test program to trigger the invalid signature test.

Refs osquery/osquery#7359

2021-10-28 15:28 UTC, ameily commented
The invalid signature test is still failing for arm64 architectures. The test itself is labeled as a hack because it copies a signed binary, `ls`, and modifies several bytes, hopefully triggering an invalid signature. The problem appears to be that the arm64 code section is not being modified so the arm64 code section is always valid. I tried bumping up the number of bytes being modified which eventually corrupts the entire signature, not just the arm64 code section.

I've verified the results against `codesign`, so the test itself is working properly.

2021-10-28 16:50 UTC, ameily commented
I think I figured it out. I made it so that the `test_get_invalid_signature` test actually modifies one byte in the middle of *each* architecture slice. This may be overkill, but, assuming that the structure for universal binaries doesn't change, should work as new architectures are added.

2021-10-29 12:13 UTC, alessandrogario requested changes

2021-10-29 12:13 UTC, alessandrogario commented on osquery/tables/system/tests/CMakeLists.txt
> +  add_executable(unsigned_test darwin/unsigned_test.cpp)
In the upcoming CI changes, we'll package all the test binaries and send them to the Catalina worker; can this be changed to something like this (warning: pseudocode)?

```cmake
add_executable(unsigned_test ..)

add_custom_command(
  OUTPUT "${TEST_CONFIGS_DIR}/unsigned_test"
  DEPENDS unsigned_test
  COMMAND "${CMAKE_COMMAND}" -E $<TARGET_FILE:unsigned_test> "${TEST_CONFIGS_DIR}/unsigned_test_temp"
  COMMAND codesign ... "${TEST_CONFIGS_DIR}/unsigned_test_temp"
  COMMAND "${CMAKE_COMMAND}" -E rename  "${TEST_CONFIGS_DIR}/unsigned_test_temp" "${TEST_CONFIGS_DIR}/unsigned_test"
  VERBATIM
  COMMENT "Generating unsigned_test..."
)

add_custom_target(unsigned_test_builder
  DEPENDS "${TEST_CONFIGS_DIR}/unsigned_test"
)

# Make sure that the data directory is generated before the unsigned_test data
add_dependencies(unsigned_test_builder
  osquery_tools_test_configfiles
)

# Make sure that the data is built before the test
add_dependencies(osquery_tables_system_darwin_tests-test
  unsigned_test_builder
)
```

2021-10-29 14:28 UTC, ameily commented
@alessandrogario I believe I addressed your cmake feedback and updated the test to use the new output location, `test_configs/unsigned_test`

2021-11-04 20:10 UTC, mike-myers-tob commented on osquery/tables/system/tests/darwin/unsigned_test.cpp
> +}
nitpick: end this file with a newline

2021-11-04 20:24 UTC, mike-myers-tob commented on tools/ci/scripts/package_tests.sh
> +  printf "Generating the launcher..\n"
Nitpick: some of the printf statement strings end in a `..` instead of a `...`

2021-11-04 20:26 UTC, mike-myers-tob commented
Ok, I verified that it builds and passes tests on macOS 12 (x86 VM). I like the improvements to the formerly "hacky" signature invalidation method during the signature tests.

Code looks good, just need @alessandrogario to confirm if the conflicted CI file can be resolved so we can merge this PR.

2021-11-04 21:08 UTC, ameily commented
@mike-myers-tob I rebased from `feature/m1-support` which got rid of the CI conflict and addressed your other feedback.

2021-11-04 22:37 UTC, merged